### ISSUE TITLE
Recomendação em UsuarioLogin

### ISSUE THREAD

**Issue by GustavoBoaz** [EduCastroo/turma37gen#5]
No documento **UsuarioLogin.java**:

- [ ]  Colocar atributos de acordo com o exemplo abaixo
- [ ] Incluir Getter e setter de todos eles

exemplo:
```java
private long id;
private String nome;
private String usuario;
private String foto;
private String senha;
private String token;
```

**Comment by EduCastroo** [comment]
chora agora, ri depois!

**Comment by EduCastroo** [comment]
Voltei pra dizer que resolvi!
